services:
  backend:
    volumes:
      - ./backend/app:/app/app  # Hot reload for backend code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  # Enable hot reload

  frontend:
    volumes:
      - ./frontend:/app         # Mount source code for hot reload
      - /app/node_modules       # Preserve node_modules from Docker build
    command: npm run dev        # Use standard npm script (now works with preserved deps)